### ISSUE TITLE
Error:  Essentials API is called before Essentials is loaded

### ISSUE THREAD

**Issue by SrBedrock** [PlaceholderAPI/Essentials-Expansion#20]
When shutting down the server, the error is sent to the console:

```
[13:31:57 WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.10.5 generated an exception while executing task 124
java.lang.RuntimeException: Essentials API is called before Essentials is loaded.
at com.earth2me.essentials.api.Economy.getUserByName(Economy.java:64) ~[?:?]
at com.earth2me.essentials.api.Economy.getMoneyExact(Economy.java:111) ~[?:?]
at com.earth2me.essentials.api.Economy.getMoney(Economy.java:100) ~[?:?]
at net.milkbowl.vault.economy.plugins.Economy_Essentials.getBalance(Economy_Essentials.java:79) ~[?:?]
at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:22) ~[?:?]
at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:220) ~[?:?]
at com.extendedclip.papi.expansion.vault.BalTopTask.run(BalTopTask.java:48) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Tuinity-"e8f291f"]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Tuinity-"e8f291f"]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Tuinity-"e8f291f"]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by Starmism** [comment]
That is an error with the Vault expansion, not the Essentials expansion. Try with latest builds.
