### ISSUE TITLE
Placeholder request for Essentials AFK Reason messages - "/afk (reason)"

### ISSUE THREAD

**Issue by axemwa** [PlaceholderAPI/Essentials-Expansion#9]
Suggestion/request to add an essentials placeholder that outputs player AFK reason messages 
In essentials you can do the command "/afk (reason)" where reason is the extra arguement(s) that the player types in to explain why they are AFK and have a placeholder that might suit it here "%essentials_afk_reason%"

Referred by essentials dev md678685
https://github.com/EssentialsX/Essentials/issues/2390#issuecomment-456805062

**Comment by darbyjack** [comment]
Can you even set custom messages for /afk? When I do it, it just says "player not found".

**Comment by axemwa** [comment]
Yes, see here fourth line down - https://essinfo.xeya.me/permissions.php

**Comment by axemwa** [comment]
Essentials | afk | essentials.afk.message | Allow access to settings an afk message.
-- | -- | -- | --

**Comment by darbyjack** [comment]
Ahh I see it now. It just never tells you the message you set when you're AFK. I'll add it in shortly.

**Comment by darbyjack** [comment]
It's in, just get the updated expansion from the ecloud and you're good to go.

**Comment by axemwa** [comment]
ow wow thanx heaps that was quick 


> 
> 
> Ahh I see it now. It just never tells you the message you set when you're AFK. I'll add it in shortly.

and its does tell you the afk reason in chat just as long as it was typed in after /afk, auto-afk won't automatically set the reason the reason must be set everytime if wanting the reason to show

**Comment by axemwa** [comment]
and did u use this? %essentials_afk_reason%

**Comment by darbyjack** [comment]
Yes

**Comment by axemwa** [comment]
cool tyvm

**Comment by axemwa** [comment]
Expansion verison 1.2.1? Can't seem to get it to parse...

**Comment by darbyjack** [comment]
Reboot the server.

**Comment by axemwa** [comment]
that did it, ty

**Comment by axemwa** [comment]
Don't forget to add to the list on github and/or spigot
Btw found an error when trying to use the parse on thy self
https://pastebin.com/97NRqWev

**Comment by axemwa** [comment]
^

**Comment by axemwa** [comment]
@darbyjack 
Actually the error returns when the player doesn't have an AFK message set can you plz fix?

**Comment by darbyjack** [comment]
Should be good.

**Comment by axemwa** [comment]
did u just fix it? - https://pastebin.com/97NRqWev

**Comment by axemwa** [comment]
I can't use it in deluxe menus that's all

**Comment by axemwa** [comment]
When I try to use the placeholder in deluxe menus I get this
`[19:14:20 WARN]: [DeluxeMenus] Plugin DeluxeMenus v1.10.5 generated an exception while executing task 47793
java.lang.NullPointerException: null
        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[patched_1.13.2.jar:git-Paper-508]
        at com.extendedclip.papi.expansion.essentials.EssentialsExpansion.onPlaceholderRequest(EssentialsExpansion.java:177) ~[?:?]
        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:237) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:377) ~[?:?]
        at com.extendedclip.deluxemenus.menu.MenuItem.getItemStack(MenuItem.java:360) ~[?:?]
        at com.extendedclip.deluxemenus.menu.Menu$2.run(Menu.java:232) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-508]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-508]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-508]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]`

**Comment by darbyjack** [comment]
You will need to reboot your server and make sure you have expansion version 1.2.2

**Comment by axemwa** [comment]
Thanx that fixed it, that was quick!

**Comment by axemwa** [comment]
latest version wouldnt download ingame so I go it manually from the site
